name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.GITHUB_REPOSITORY }}:${{ env.GITHUB_SHA }} --build-arg GIT_REPOSITORY=${{ env.GH_REPOSITORY }} --build-arg GIT_USERNAME=${{env.GITHUB_OWNER }} --build-arg GIT_PASSWORD=${{ env.GH_SCS_TOKEN }}
    
    - uses: docker/login-action@v2
    - name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - uses: docker/build-push-action@v4
    - name: Build and push        
      with:
        push: true
        tags: ${{ env.GITHUB_REPOSITORY }}:${{ env.GITHUB_SHA }}
